CC      ?= cc
CFLAGS  ?= -O2 -Wall -Wextra -Wshadow -Wpedantic -std=c11
AR      ?= ar
INSTALL ?= install

PREFIX    ?= /usr/local
LIBDIR    ?= $(PREFIX)/lib
INCLUDEDIR?= $(PREFIX)/include
PKGCONFIGDIR ?= $(LIBDIR)/pkgconfig

VERSION   = $(shell cat VERSION | tr -d '[:space:]')
DESCRIPTION = Standalone DER/PEM/Base64 codec for post-quantum key serialization

# Individual translation units (build from these for fast incremental recompiles)
TU_SRCS  = src/tlv.c src/builder.c src/parser.c src/base64.c src/pem.c
TU_OBJS  = $(TU_SRCS:.c=.o)

# Single-file distribution artifact (generated by scripts/concat.sh)
SINGLE_SRC = src/pqc_asn1.c

HDR      = include/pqc_asn1.h
INT_HDR  = src/pqc_asn1_internal.h
LIB      = libpqc_asn1.a
TEST_SRC = test/test_pqc_asn1.c
TEST_BIN = test/test_pqc_asn1

INCLUDES = -Iinclude -Isrc

.PHONY: all clean test install uninstall concat

all: $(LIB)

# Build each TU separately for fast incremental recompiles.
$(TU_OBJS): %.o: %.c $(HDR) $(INT_HDR)
	$(CC) $(CFLAGS) $(INCLUDES) -c -o $@ $<

$(LIB): $(TU_OBJS)
	$(AR) rcs $@ $^

# Regenerate the single-file distribution artifact from individual TUs.
concat: $(TU_SRCS) $(INT_HDR)
	./scripts/concat.sh $(SINGLE_SRC)

$(TEST_BIN): $(TEST_SRC) $(LIB) $(HDR)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $(TEST_SRC) -L. -lpqc_asn1 $(LDFLAGS)

test: $(TEST_BIN)
	./$(TEST_BIN)

install: $(LIB)
	$(INSTALL) -d $(DESTDIR)$(LIBDIR)
	$(INSTALL) -d $(DESTDIR)$(INCLUDEDIR)
	$(INSTALL) -d $(DESTDIR)$(PKGCONFIGDIR)
	$(INSTALL) -m 644 $(LIB) $(DESTDIR)$(LIBDIR)/
	$(INSTALL) -m 644 $(HDR) $(DESTDIR)$(INCLUDEDIR)/
	@echo 'prefix=$(PREFIX)' > $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'exec_prefix=$${prefix}' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'libdir=$(LIBDIR)' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'includedir=$(INCLUDEDIR)' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo '' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'Name: pqc_asn1' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'Description: $(DESCRIPTION)' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'Version: $(VERSION)' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'Libs: -L$${libdir} -lpqc_asn1' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc
	@echo 'Cflags: -I$${includedir}' >> $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc

uninstall:
	rm -f $(DESTDIR)$(LIBDIR)/$(LIB)
	rm -f $(DESTDIR)$(INCLUDEDIR)/pqc_asn1.h
	rm -f $(DESTDIR)$(PKGCONFIGDIR)/pqc_asn1.pc

clean:
	rm -f $(TU_OBJS) src/pqc_asn1.o $(LIB) $(TEST_BIN)
